# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: model_trainer

on:
  schedule:
    - cron: '0 0 1 * *' #runs every 2hours
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: run main scripts
      run: |
        python backend/components/dataIngestion.py

    - name: Commit files
      run: |
        git config --local user.email "niceiyke@github.com"
        git config --local user.name "Niceiyk"
        git commit -a -m "updated db"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master